### ISSUE TITLE
`fn` and `let` keywork in rust-lang can be improvement.

### ISSUE THREAD

**Issue by WindSoilder** [connor4312/codesong#1]
Compared to `python` function definition keywork `define`:

![图片](https://user-images.githubusercontent.com/22256154/96987056-10037e80-1555-11eb-98aa-ad10aa65ae60.png)

And rust function definition keywork `fn`, variable definition `let`:

![图片](https://user-images.githubusercontent.com/22256154/96987172-375a4b80-1555-11eb-8c07-91a1b8cfaf74.png)

I think `fn` and `let` can have the same color as `define`, current color is too similar to `comment` color, which causes less readable.

By the way,,sorry for my little poor English :-(

**Comment by connor4312** [comment]
Thanks, it looks like RLS doesn't actually have a specific type for "let", so I just colored all "keyword.other.rust" to green. Doesn't look like it messes anything up, but if it does let me know.
