### ISSUE TITLE
'render whitespace' characters are hardly visible

### ISSUE THREAD

**Issue by perlick** [connor4312/codesong#2]
when setting "editor.renderWhitespace": "all". you can see the individual tabs and spaces on each line. The whitespace marks are visible enough when highlighted but they're hardly noticeable normally. 

I think changing them to a lighter shade of gray when not highlighted would be better.

**Comment by connor4312** [comment]
I like them how are are, but you're free to add something like this to your user settings:

```js
"workbench.colorCustomizations": {
  "[Codesong]": {
    "editorWhitespace.foreground": "#ffffff22"
  }
},
```
